-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.6.3).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -Wno-incomplete-patterns -Wno-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module GeneratedParser.Wok.Par
  ( happyError
  , myLexer
  , pModule
  ) where

import Prelude

import qualified GeneratedParser.Wok.Abs
import GeneratedParser.Wok.Lex
import qualified Data.Text

}

%name pModule Module
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '('       { PT _ (TS _ 1)     }
  ')'       { PT _ (TS _ 2)     }
  ','       { PT _ (TS _ 3)     }
  '->'      { PT _ (TS _ 4)     }
  ':'       { PT _ (TS _ 5)     }
  '::'      { PT _ (TS _ 6)     }
  ';'       { PT _ (TS _ 7)     }
  '='       { PT _ (TS _ 8)     }
  '['       { PT _ (TS _ 9)     }
  '\\'      { PT _ (TS _ 10)    }
  ']'       { PT _ (TS _ 11)    }
  '_'       { PT _ (TS _ 12)    }
  '`'       { PT _ (TS _ 13)    }
  'case'    { PT _ (TS _ 14)    }
  'data'    { PT _ (TS _ 15)    }
  'else'    { PT _ (TS _ 16)    }
  'fixity'  { PT _ (TS _ 17)    }
  'if'      { PT _ (TS _ 18)    }
  'in'      { PT _ (TS _ 19)    }
  'left'    { PT _ (TS _ 20)    }
  'let'     { PT _ (TS _ 21)    }
  'looser'  { PT _ (TS _ 22)    }
  'of'      { PT _ (TS _ 23)    }
  'right'   { PT _ (TS _ 24)    }
  'than'    { PT _ (TS _ 25)    }
  'then'    { PT _ (TS _ 26)    }
  'tighter' { PT _ (TS _ 27)    }
  'where'   { PT _ (TS _ 28)    }
  '{'       { PT _ (TS _ 29)    }
  '|'       { PT _ (TS _ 30)    }
  '}'       { PT _ (TS _ 31)    }
  L_charac  { PT _ (TC $$)      }
  L_quoted  { PT _ (TL $$)      }
  L_WokInt  { PT _ (T_WokInt _) }
  L_VarId   { PT _ (T_VarId _)  }
  L_VarSym  { PT _ (T_VarSym _) }

%%

Char    :: { Char }
Char     : L_charac { (read (Data.Text.unpack $1)) :: Char }

String  :: { String }
String   : L_quoted { (Data.Text.unpack $1) }

WokInt :: { GeneratedParser.Wok.Abs.WokInt }
WokInt  : L_WokInt { GeneratedParser.Wok.Abs.WokInt (mkPosToken $1) }

VarId :: { GeneratedParser.Wok.Abs.VarId }
VarId  : L_VarId { GeneratedParser.Wok.Abs.VarId (mkPosToken $1) }

VarSym :: { GeneratedParser.Wok.Abs.VarSym }
VarSym  : L_VarSym { GeneratedParser.Wok.Abs.VarSym (mkPosToken $1) }

Module :: { GeneratedParser.Wok.Abs.Module }
Module : ListDecl { GeneratedParser.Wok.Abs.Module $1 }

Decl :: { GeneratedParser.Wok.Abs.Decl }
Decl
  : FunLHS '=' Exp MaybeWhere { GeneratedParser.Wok.Abs.DEqn $1 $3 $4 }
  | VarId ListVarIdComma ':' Type { GeneratedParser.Wok.Abs.DSig $1 $2 $4 }
  | 'data' VarId ListVarId '=' ListConDef { GeneratedParser.Wok.Abs.DData $2 $3 $5 }
  | 'fixity' FixName FixAssoc ListFixRel { GeneratedParser.Wok.Abs.DFixity $2 $3 $4 }

ListDecl :: { [GeneratedParser.Wok.Abs.Decl] }
ListDecl
  : {- empty -} { [] }
  | Decl { (:[]) $1 }
  | Decl ';' ListDecl { (:) $1 $3 }

VarIdComma :: { GeneratedParser.Wok.Abs.VarIdComma }
VarIdComma : ',' VarId { GeneratedParser.Wok.Abs.VICons $2 }

ListVarIdComma :: { [GeneratedParser.Wok.Abs.VarIdComma] }
ListVarIdComma
  : {- empty -} { [] } | VarIdComma ListVarIdComma { (:) $1 $2 }

ListVarId :: { [GeneratedParser.Wok.Abs.VarId] }
ListVarId : {- empty -} { [] } | VarId ListVarId { (:) $1 $2 }

FunLHS :: { GeneratedParser.Wok.Abs.FunLHS }
FunLHS
  : FunName ListAtomPat { GeneratedParser.Wok.Abs.LHSPre $1 $2 }
  | AtomPat VarSym AtomPat { GeneratedParser.Wok.Abs.LHSInfSym $1 $2 $3 }
  | AtomPat '`' VarId '`' AtomPat { GeneratedParser.Wok.Abs.LHSInfBT $1 $3 $5 }

FunName :: { GeneratedParser.Wok.Abs.FunName }
FunName
  : VarId { GeneratedParser.Wok.Abs.FNBare $1 }
  | VarSym { GeneratedParser.Wok.Abs.FNBareSym $1 }
  | '(' VarSym ')' { GeneratedParser.Wok.Abs.FNParen $2 }

Pat :: { GeneratedParser.Wok.Abs.Pat }
Pat
  : VarId AtomPat ListAtomPat { GeneratedParser.Wok.Abs.PApp $1 $2 $3 }
  | AtomPat '::' Pat { GeneratedParser.Wok.Abs.PCons $1 $3 }
  | AtomPat { GeneratedParser.Wok.Abs.PAtom $1 }

AtomPat :: { GeneratedParser.Wok.Abs.AtomPat }
AtomPat
  : VarId { GeneratedParser.Wok.Abs.APVar $1 }
  | '_' { GeneratedParser.Wok.Abs.APWild }
  | WokInt { GeneratedParser.Wok.Abs.APLitI $1 }
  | String { GeneratedParser.Wok.Abs.APLitS $1 }
  | Char { GeneratedParser.Wok.Abs.APLitC $1 }
  | '(' Pat ',' ListPat ')' { GeneratedParser.Wok.Abs.APTuple $2 $4 }
  | '[' ListPat ']' { GeneratedParser.Wok.Abs.APList $2 }
  | '(' Pat ')' { GeneratedParser.Wok.Abs.APParen $2 }

ListAtomPat :: { [GeneratedParser.Wok.Abs.AtomPat] }
ListAtomPat
  : {- empty -} { [] } | AtomPat ListAtomPat { (:) $1 $2 }

ListPat :: { [GeneratedParser.Wok.Abs.Pat] }
ListPat
  : {- empty -} { [] }
  | Pat { (:[]) $1 }
  | Pat ',' ListPat { (:) $1 $3 }

Type :: { GeneratedParser.Wok.Abs.Type }
Type
  : Type1 '->' Type { GeneratedParser.Wok.Abs.TFun $1 $3 }
  | Type1 { $1 }

Type1 :: { GeneratedParser.Wok.Abs.Type }
Type1
  : Type1 Type2 { GeneratedParser.Wok.Abs.TApp $1 $2 } | Type2 { $1 }

Type2 :: { GeneratedParser.Wok.Abs.Type }
Type2
  : VarId { GeneratedParser.Wok.Abs.TVar $1 }
  | '[' Type ']' { GeneratedParser.Wok.Abs.TList $2 }
  | '(' Type ',' ListType ')' { GeneratedParser.Wok.Abs.TTuple $2 $4 }
  | '(' Type ')' { GeneratedParser.Wok.Abs.TParen $2 }

ListType :: { [GeneratedParser.Wok.Abs.Type] }
ListType
  : {- empty -} { [] }
  | Type { (:[]) $1 }
  | Type ',' ListType { (:) $1 $3 }

ConDef :: { GeneratedParser.Wok.Abs.ConDef }
ConDef : VarId ListType2 { GeneratedParser.Wok.Abs.ConDef $1 $2 }

ListConDef :: { [GeneratedParser.Wok.Abs.ConDef] }
ListConDef
  : {- empty -} { [] }
  | ConDef { (:[]) $1 }
  | ConDef '|' ListConDef { (:) $1 $3 }

ListType2 :: { [GeneratedParser.Wok.Abs.Type] }
ListType2 : {- empty -} { [] } | Type2 ListType2 { (:) $1 $2 }

FixName :: { GeneratedParser.Wok.Abs.FixName }
FixName
  : VarSym { GeneratedParser.Wok.Abs.FNSym $1 }
  | VarId { GeneratedParser.Wok.Abs.FNAlpha $1 }

FixAssoc :: { GeneratedParser.Wok.Abs.FixAssoc }
FixAssoc
  : 'left' { GeneratedParser.Wok.Abs.FALeft }
  | 'right' { GeneratedParser.Wok.Abs.FARight }

FixRel :: { GeneratedParser.Wok.Abs.FixRel }
FixRel
  : 'tighter' 'than' FixName { GeneratedParser.Wok.Abs.FRTight $3 }
  | 'looser' 'than' FixName { GeneratedParser.Wok.Abs.FRLoose $3 }

ListFixRel :: { [GeneratedParser.Wok.Abs.FixRel] }
ListFixRel : {- empty -} { [] } | FixRel ListFixRel { (:) $1 $2 }

Exp :: { GeneratedParser.Wok.Abs.Exp }
Exp : Exp1 ListInfixTail { GeneratedParser.Wok.Abs.EExpr $1 $2 }

InfixTail :: { GeneratedParser.Wok.Abs.InfixTail }
InfixTail : InfixOp Exp1 { GeneratedParser.Wok.Abs.ITail $1 $2 }

ListInfixTail :: { [GeneratedParser.Wok.Abs.InfixTail] }
ListInfixTail
  : {- empty -} { [] } | InfixTail ListInfixTail { (:) $1 $2 }

InfixOp :: { GeneratedParser.Wok.Abs.InfixOp }
InfixOp
  : VarSym { GeneratedParser.Wok.Abs.IOSym $1 }
  | '`' VarId '`' { GeneratedParser.Wok.Abs.IOBT $2 }

Exp1 :: { GeneratedParser.Wok.Abs.Exp }
Exp1
  : Exp1 Exp2 { GeneratedParser.Wok.Abs.EApp $1 $2 } | Exp2 { $1 }

Exp2 :: { GeneratedParser.Wok.Abs.Exp }
Exp2
  : VarId { GeneratedParser.Wok.Abs.EVar $1 }
  | WokInt { GeneratedParser.Wok.Abs.ELitI $1 }
  | String { GeneratedParser.Wok.Abs.ELitS $1 }
  | Char { GeneratedParser.Wok.Abs.ELitC $1 }
  | '(' Exp ')' { GeneratedParser.Wok.Abs.EParen $2 }
  | '(' VarSym ')' { GeneratedParser.Wok.Abs.EParenOp $2 }
  | '[' ListExp ']' { GeneratedParser.Wok.Abs.EList $2 }
  | '(' Exp ',' ListExp ')' { GeneratedParser.Wok.Abs.ETuple $2 $4 }
  | '\\' ListAtomPat '->' Exp { GeneratedParser.Wok.Abs.ELam $2 $4 }
  | 'let' '{' ListLocalDecl '}' 'in' Exp { GeneratedParser.Wok.Abs.ELet $3 $6 }
  | 'case' Exp 'of' '{' ListAlt '}' { GeneratedParser.Wok.Abs.ECase $2 $5 }
  | 'if' Exp 'then' Exp 'else' Exp { GeneratedParser.Wok.Abs.EIf $2 $4 $6 }

ListExp :: { [GeneratedParser.Wok.Abs.Exp] }
ListExp
  : {- empty -} { [] }
  | Exp { (:[]) $1 }
  | Exp ',' ListExp { (:) $1 $3 }

LocalDecl :: { GeneratedParser.Wok.Abs.LocalDecl }
LocalDecl
  : FunLHS '=' Exp MaybeWhere { GeneratedParser.Wok.Abs.LDEqn $1 $3 $4 }
  | VarId ListVarIdComma ':' Type { GeneratedParser.Wok.Abs.LDSig $1 $2 $4 }

ListLocalDecl :: { [GeneratedParser.Wok.Abs.LocalDecl] }
ListLocalDecl
  : {- empty -} { [] }
  | LocalDecl { (:[]) $1 }
  | LocalDecl ';' ListLocalDecl { (:) $1 $3 }

MaybeWhere :: { GeneratedParser.Wok.Abs.MaybeWhere }
MaybeWhere
  : {- empty -} { GeneratedParser.Wok.Abs.NoWhere }
  | 'where' '{' ListLocalDecl '}' { GeneratedParser.Wok.Abs.WithWh $3 }

Alt :: { GeneratedParser.Wok.Abs.Alt }
Alt
  : Pat '->' Exp MaybeWhere { GeneratedParser.Wok.Abs.AltC $1 $3 $4 }

ListAlt :: { [GeneratedParser.Wok.Abs.Alt] }
ListAlt
  : {- empty -} { [] }
  | Alt { (:[]) $1 }
  | Alt ';' ListAlt { (:) $1 $3 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: Data.Text.Text -> [Token]
myLexer = tokens

}

