-- File generated by the BNF Converter (bnfc 2.9.6.3).

{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language Wok.

module GeneratedParser.Wok.Abs where

import Prelude (Char, String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Int, Maybe(..)
  )

import qualified Data.Text

data Module = Module [Decl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Decl
    = DEqn FunLHS Exp MaybeWhere
    | DSig SigName [SigNameComma] Type
    | DData ConId [VarId] [ConDef]
    | DFixity FixName FixAssoc [FixRel]
    | DModule ModPath
    | DImport ModPath
    | DUse ModPath
    | DLocal Decl
    | DReserved ReservedKw
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ModPath = MPName ConId | MPDot ModPath ConId
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ReservedKw
    = ReservedKw_contract
    | ReservedKw_type
    | ReservedKw_class
    | ReservedKw_instance
    | ReservedKw_deriving
    | ReservedKw_forall
    | ReservedKw_do
    | ReservedKw_record
    | ReservedKw_row
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SigName = SNBare VarId | SNParen VarSym
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SigNameComma = SNCons SigName
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FunLHS
    = LHSPre FunName [AtomPat]
    | LHSInfSym AtomPat VarSym AtomPat
    | LHSInfBT AtomPat VarId AtomPat
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FunName = FNBare VarId | FNBareSym VarSym | FNParen VarSym
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Pat
    = PApp ModPath AtomPat [AtomPat]
    | PCons AtomPat Pat
    | PAtom AtomPat
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data AtomPat
    = APVar VarId
    | APCon ModPath
    | APWild
    | APLitI WokInt
    | APLitS String
    | APLitC Char
    | APTuple Pat [Pat]
    | APList [Pat]
    | APParen Pat
    | PUnit
    | PRecord ConId [RecordFieldPat]
    | PRecordOpen ConId [RecordFieldPat] PatRowTail
    | PRecordWild ConId PatRowTail
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RecordFieldPat = RFPat VarId Pat
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data PatRowTail = PRTNamed VarId | PRTAnon
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type
    = TFun Type Type
    | TApp Type Type
    | TVar VarId
    | TCon ModPath
    | TList Type
    | TTuple Type [Type]
    | TParen Type
    | TUnit
    | TExtend Type VarSym RowContrib
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RowContrib = RCAnon [RecordFieldType] | RCVar VarId
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConDef
    = ConDef ConId [Type]
    | ConDefRec ConId [RecordFieldType]
    | ConDefRecElide [RecordFieldType]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RecordFieldType = RFType VarId Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FixName = FNSym VarSym | FNAlpha VarId
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FixAssoc = FALeft | FARight
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FixRel = FRTight FixName | FRLoose FixName
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp
    = EExpr Exp [InfixTail]
    | EApp Exp Exp
    | EVar VarId
    | ECon ConId
    | EProj Exp VarId
    | EProjC Exp ConId
    | ERecord ConId [RecordFieldExpr]
    | ERecordExt ConId Exp MaybeTrailing
    | ELitI WokInt
    | ELitS String
    | ELitC Char
    | EParen Exp
    | EParenOp VarSym
    | EUnit
    | EList [Exp]
    | ETuple Exp [Exp]
    | ELam [AtomPat] Exp
    | ELet [LocalDecl] Exp
    | ECase Exp [Alt]
    | EIf Exp Exp Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data InfixTail = ITail InfixOp Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data InfixOp = IOSym VarSym | IOBT VarId
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data MaybeTrailing = TFNone | TFSome [RecordFieldExpr]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RecordFieldExpr = RFExpr VarId Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LocalDecl
    = LDEqn FunLHS Exp MaybeWhere | LDSig SigName [SigNameComma] Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data MaybeWhere = NoWhere | WithWh [LocalDecl]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Alt = AltC Pat Exp MaybeWhere
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype WokInt = WokInt ((C.Int, C.Int), Data.Text.Text)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype ConId = ConId ((C.Int, C.Int), Data.Text.Text)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype VarId = VarId ((C.Int, C.Int), Data.Text.Text)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype VarSym = VarSym ((C.Int, C.Int), Data.Text.Text)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition WokInt where
  hasPosition (WokInt (p, _)) = C.Just p

instance HasPosition ConId where
  hasPosition (ConId (p, _)) = C.Just p

instance HasPosition VarId where
  hasPosition (VarId (p, _)) = C.Just p

instance HasPosition VarSym where
  hasPosition (VarSym (p, _)) = C.Just p

