-- -*- haskell -*- File generated by the BNF Converter (bnfc 2.9.6.3).

-- Parser definition for use with Happy
{
{-# OPTIONS_GHC -Wno-incomplete-patterns -Wno-overlapping-patterns #-}
{-# LANGUAGE PatternSynonyms #-}

module GeneratedParser.Wok.Par
  ( happyError
  , myLexer
  , pModule
  ) where

import Prelude

import qualified GeneratedParser.Wok.Abs
import GeneratedParser.Wok.Lex
import qualified Data.Text

}

%name pModule Module
-- no lexer declaration
%monad { Err } { (>>=) } { return }
%tokentype {Token}
%token
  '('        { PT _ (TS _ 1)     }
  ')'        { PT _ (TS _ 2)     }
  ','        { PT _ (TS _ 3)     }
  '->'       { PT _ (TS _ 4)     }
  '.'        { PT _ (TS _ 5)     }
  '..'       { PT _ (TS _ 6)     }
  ':'        { PT _ (TS _ 7)     }
  '::'       { PT _ (TS _ 8)     }
  ';'        { PT _ (TS _ 9)     }
  '='        { PT _ (TS _ 10)    }
  '=>'       { PT _ (TS _ 11)    }
  '['        { PT _ (TS _ 12)    }
  '\\'       { PT _ (TS _ 13)    }
  ']'        { PT _ (TS _ 14)    }
  '_'        { PT _ (TS _ 15)    }
  '`'        { PT _ (TS _ 16)    }
  'as'       { PT _ (TS _ 17)    }
  'case'     { PT _ (TS _ 18)    }
  'class'    { PT _ (TS _ 19)    }
  'contract' { PT _ (TS _ 20)    }
  'ctl'      { PT _ (TS _ 21)    }
  'data'     { PT _ (TS _ 22)    }
  'deriving' { PT _ (TS _ 23)    }
  'do'       { PT _ (TS _ 24)    }
  'eff'      { PT _ (TS _ 25)    }
  'effect'   { PT _ (TS _ 26)    }
  'else'     { PT _ (TS _ 27)    }
  'extern'   { PT _ (TS _ 28)    }
  'fixity'   { PT _ (TS _ 29)    }
  'forall'   { PT _ (TS _ 30)    }
  'foreign'  { PT _ (TS _ 31)    }
  'free'     { PT _ (TS _ 32)    }
  'fun'      { PT _ (TS _ 33)    }
  'if'       { PT _ (TS _ 34)    }
  'import'   { PT _ (TS _ 35)    }
  'in'       { PT _ (TS _ 36)    }
  'instance' { PT _ (TS _ 37)    }
  'left'     { PT _ (TS _ 38)    }
  'let'      { PT _ (TS _ 39)    }
  'local'    { PT _ (TS _ 40)    }
  'looser'   { PT _ (TS _ 41)    }
  'module'   { PT _ (TS _ 42)    }
  'of'       { PT _ (TS _ 43)    }
  'owned'    { PT _ (TS _ 44)    }
  'record'   { PT _ (TS _ 45)    }
  'right'    { PT _ (TS _ 46)    }
  'row'      { PT _ (TS _ 47)    }
  'than'     { PT _ (TS _ 48)    }
  'then'     { PT _ (TS _ 49)    }
  'tighter'  { PT _ (TS _ 50)    }
  'type'     { PT _ (TS _ 51)    }
  'use'      { PT _ (TS _ 52)    }
  'where'    { PT _ (TS _ 53)    }
  'with'     { PT _ (TS _ 54)    }
  '{'        { PT _ (TS _ 55)    }
  '|'        { PT _ (TS _ 56)    }
  '}'        { PT _ (TS _ 57)    }
  L_charac   { PT _ (TC $$)      }
  L_quoted   { PT _ (TL $$)      }
  L_WokInt   { PT _ (T_WokInt _) }
  L_ConId    { PT _ (T_ConId _)  }
  L_VarId    { PT _ (T_VarId _)  }
  L_VarSym   { PT _ (T_VarSym _) }

%%

Char    :: { Char }
Char     : L_charac { (read (Data.Text.unpack $1)) :: Char }

String  :: { String }
String   : L_quoted { (Data.Text.unpack $1) }

WokInt :: { GeneratedParser.Wok.Abs.WokInt }
WokInt  : L_WokInt { GeneratedParser.Wok.Abs.WokInt (mkPosToken $1) }

ConId :: { GeneratedParser.Wok.Abs.ConId }
ConId  : L_ConId { GeneratedParser.Wok.Abs.ConId (mkPosToken $1) }

VarId :: { GeneratedParser.Wok.Abs.VarId }
VarId  : L_VarId { GeneratedParser.Wok.Abs.VarId (mkPosToken $1) }

VarSym :: { GeneratedParser.Wok.Abs.VarSym }
VarSym  : L_VarSym { GeneratedParser.Wok.Abs.VarSym (mkPosToken $1) }

Module :: { GeneratedParser.Wok.Abs.Module }
Module : ListDecl { GeneratedParser.Wok.Abs.Module $1 }

Decl :: { GeneratedParser.Wok.Abs.Decl }
Decl
  : FunLHS '=' Exp MaybeWhere { GeneratedParser.Wok.Abs.DEqn $1 $3 $4 }
  | SigName ListSigNameComma ':' Type { GeneratedParser.Wok.Abs.DSig $1 $2 $4 }
  | 'extern' SigName ListSigNameComma ':' Type { GeneratedParser.Wok.Abs.DExtern $2 $3 $5 }
  | 'data' ConId ListTyParam '=' ListConDef { GeneratedParser.Wok.Abs.DData $2 $3 $5 }
  | 'extern' 'data' ConId ListTyParam '=' ListConDef { GeneratedParser.Wok.Abs.DExternData $3 $4 $6 }
  | 'extern' 'type' ConId ListTyParam { GeneratedParser.Wok.Abs.DExternType $3 $4 }
  | 'effect' ConId ListVarId '=' '{' ListRecordFieldType '}' { GeneratedParser.Wok.Abs.DEffect $2 $3 $6 }
  | 'fixity' FixName FixAssoc ListFixRel { GeneratedParser.Wok.Abs.DFixity $2 $3 $4 }
  | 'class' ConId ListVarId 'where' '{' ListClassEntry '}' { GeneratedParser.Wok.Abs.DClass $2 $3 $6 }
  | 'instance' InstHead 'where' '{' ListInstEntry '}' { GeneratedParser.Wok.Abs.DInstance $2 $5 }
  | 'foreign' 'module' ConId String ForeignFree 'where' '{' ListForeignMember '}' { GeneratedParser.Wok.Abs.DForeign $3 $4 $5 $8 }
  | 'module' ModPath { GeneratedParser.Wok.Abs.DModule $2 }
  | 'import' ModPath { GeneratedParser.Wok.Abs.DImport $2 }
  | 'use' ModPath { GeneratedParser.Wok.Abs.DUse $2 }
  | 'local' Decl { GeneratedParser.Wok.Abs.DLocal $2 }
  | ReservedKw { GeneratedParser.Wok.Abs.DReserved $1 }

ForeignFree :: { GeneratedParser.Wok.Abs.ForeignFree }
ForeignFree
  : {- empty -} { GeneratedParser.Wok.Abs.FFNone }
  | 'free' String { GeneratedParser.Wok.Abs.FFSym $2 }

ForeignMember :: { GeneratedParser.Wok.Abs.ForeignMember }
ForeignMember
  : VarId ForeignSym ':' Type { GeneratedParser.Wok.Abs.FMPlain $1 $2 $4 }
  | 'owned' VarId ForeignSym ':' Type { GeneratedParser.Wok.Abs.FMOwned $2 $3 $5 }

ForeignSym :: { GeneratedParser.Wok.Abs.ForeignSym }
ForeignSym
  : {- empty -} { GeneratedParser.Wok.Abs.FSNone }
  | String { GeneratedParser.Wok.Abs.FSName $1 }

ListForeignMember :: { [GeneratedParser.Wok.Abs.ForeignMember] }
ListForeignMember
  : {- empty -} { [] }
  | ForeignMember { (:[]) $1 }
  | ForeignMember ';' ListForeignMember { (:) $1 $3 }

InstHead :: { GeneratedParser.Wok.Abs.InstHead }
InstHead
  : ConId ListType2 { GeneratedParser.Wok.Abs.IHPlain $1 $2 }
  | '(' ListConstraint ')' '=>' ConId ListType2 { GeneratedParser.Wok.Abs.IHCtx $2 $5 $6 }

MethodName :: { GeneratedParser.Wok.Abs.MethodName }
MethodName
  : VarId { GeneratedParser.Wok.Abs.MNBare $1 }
  | '(' VarSym ')' { GeneratedParser.Wok.Abs.MNParen $2 }

ClassEntry :: { GeneratedParser.Wok.Abs.ClassEntry }
ClassEntry
  : MethodName ':' Type { GeneratedParser.Wok.Abs.CESig $1 $3 }
  | FunLHS '=' Exp { GeneratedParser.Wok.Abs.CEDefault $1 $3 }

ListClassEntry :: { [GeneratedParser.Wok.Abs.ClassEntry] }
ListClassEntry
  : {- empty -} { [] }
  | ClassEntry { (:[]) $1 }
  | ClassEntry ';' ListClassEntry { (:) $1 $3 }

InstEntry :: { GeneratedParser.Wok.Abs.InstEntry }
InstEntry : FunLHS '=' Exp { GeneratedParser.Wok.Abs.IEImpl $1 $3 }

ListInstEntry :: { [GeneratedParser.Wok.Abs.InstEntry] }
ListInstEntry
  : {- empty -} { [] }
  | InstEntry { (:[]) $1 }
  | InstEntry ';' ListInstEntry { (:) $1 $3 }

Constraint :: { GeneratedParser.Wok.Abs.Constraint }
Constraint
  : ConId ListType2 { GeneratedParser.Wok.Abs.Constraint $1 $2 }

ListConstraint :: { [GeneratedParser.Wok.Abs.Constraint] }
ListConstraint
  : {- empty -} { [] }
  | Constraint { (:[]) $1 }
  | Constraint ',' ListConstraint { (:) $1 $3 }

ListDecl :: { [GeneratedParser.Wok.Abs.Decl] }
ListDecl
  : {- empty -} { [] }
  | Decl { (:[]) $1 }
  | Decl ';' ListDecl { (:) $1 $3 }

ModPath :: { GeneratedParser.Wok.Abs.ModPath }
ModPath
  : ConId { GeneratedParser.Wok.Abs.MPName $1 }
  | ModPath '.' ConId { GeneratedParser.Wok.Abs.MPDot $1 $3 }

ReservedKw :: { GeneratedParser.Wok.Abs.ReservedKw }
ReservedKw
  : 'contract' { GeneratedParser.Wok.Abs.ReservedKw_contract }
  | 'type' { GeneratedParser.Wok.Abs.ReservedKw_type }
  | 'deriving' { GeneratedParser.Wok.Abs.ReservedKw_deriving }
  | 'forall' { GeneratedParser.Wok.Abs.ReservedKw_forall }
  | 'do' { GeneratedParser.Wok.Abs.ReservedKw_do }
  | 'record' { GeneratedParser.Wok.Abs.ReservedKw_record }
  | 'row' { GeneratedParser.Wok.Abs.ReservedKw_row }
  | 'fun' { GeneratedParser.Wok.Abs.ReservedKw_fun }
  | 'ctl' { GeneratedParser.Wok.Abs.ReservedKw_ctl }

SigName :: { GeneratedParser.Wok.Abs.SigName }
SigName
  : VarId { GeneratedParser.Wok.Abs.SNBare $1 }
  | '(' VarSym ')' { GeneratedParser.Wok.Abs.SNParen $2 }

SigNameComma :: { GeneratedParser.Wok.Abs.SigNameComma }
SigNameComma : ',' SigName { GeneratedParser.Wok.Abs.SNCons $2 }

ListSigNameComma :: { [GeneratedParser.Wok.Abs.SigNameComma] }
ListSigNameComma
  : {- empty -} { [] } | SigNameComma ListSigNameComma { (:) $1 $2 }

ListVarId :: { [GeneratedParser.Wok.Abs.VarId] }
ListVarId : {- empty -} { [] } | VarId ListVarId { (:) $1 $2 }

TyParam :: { GeneratedParser.Wok.Abs.TyParam }
TyParam
  : VarId { GeneratedParser.Wok.Abs.TPPlain $1 }
  | '(' 'row' VarId ')' { GeneratedParser.Wok.Abs.TPRow $3 }

ListTyParam :: { [GeneratedParser.Wok.Abs.TyParam] }
ListTyParam
  : {- empty -} { [] } | TyParam ListTyParam { (:) $1 $2 }

FunLHS :: { GeneratedParser.Wok.Abs.FunLHS }
FunLHS
  : FunName ListAtomPat { GeneratedParser.Wok.Abs.LHSPre $1 $2 }
  | AtomPat VarSym AtomPat { GeneratedParser.Wok.Abs.LHSInfSym $1 $2 $3 }
  | AtomPat '`' VarId '`' AtomPat { GeneratedParser.Wok.Abs.LHSInfBT $1 $3 $5 }

FunName :: { GeneratedParser.Wok.Abs.FunName }
FunName
  : VarId { GeneratedParser.Wok.Abs.FNBare $1 }
  | VarSym { GeneratedParser.Wok.Abs.FNBareSym $1 }
  | '(' VarSym ')' { GeneratedParser.Wok.Abs.FNParen $2 }

Pat :: { GeneratedParser.Wok.Abs.Pat }
Pat
  : ModPath AtomPat ListAtomPat { GeneratedParser.Wok.Abs.PApp $1 $2 $3 }
  | AtomPat '::' Pat { GeneratedParser.Wok.Abs.PCons $1 $3 }
  | AtomPat { GeneratedParser.Wok.Abs.PAtom $1 }

AtomPat :: { GeneratedParser.Wok.Abs.AtomPat }
AtomPat
  : VarId { GeneratedParser.Wok.Abs.APVar $1 }
  | ModPath { GeneratedParser.Wok.Abs.APCon $1 }
  | '_' { GeneratedParser.Wok.Abs.APWild }
  | WokInt { GeneratedParser.Wok.Abs.APLitI $1 }
  | String { GeneratedParser.Wok.Abs.APLitS $1 }
  | Char { GeneratedParser.Wok.Abs.APLitC $1 }
  | '(' Pat ',' ListPat ')' { GeneratedParser.Wok.Abs.APTuple $2 $4 }
  | '[' ListPat ']' { GeneratedParser.Wok.Abs.APList $2 }
  | '(' Pat ')' { GeneratedParser.Wok.Abs.APParen $2 }
  | '(' ')' { GeneratedParser.Wok.Abs.PUnit }
  | AtomPat 'as' VarId { GeneratedParser.Wok.Abs.APAs $1 $3 }
  | ConId '{' '}' { GeneratedParser.Wok.Abs.PRecord $1 [] }
  | ConId '{' NEListRecordFieldPat '}' { GeneratedParser.Wok.Abs.PRecord $1 (reverse $3) }
  | ConId '{' NEListRecordFieldPat ',' PatRowTail '}' { GeneratedParser.Wok.Abs.PRecordOpen $1 (reverse $3) $5 }
  | ConId '{' PatRowTail '}' { GeneratedParser.Wok.Abs.PRecordWild $1 $3 }

RecordFieldPat :: { GeneratedParser.Wok.Abs.RecordFieldPat }
RecordFieldPat
  : VarId '=' Pat { GeneratedParser.Wok.Abs.RFPat $1 $3 }

ListRecordFieldPat :: { [GeneratedParser.Wok.Abs.RecordFieldPat] }
ListRecordFieldPat
  : {- empty -} { [] }
  | RecordFieldPat { (:[]) $1 }
  | RecordFieldPat ',' ListRecordFieldPat { (:) $1 $3 }

-- PATCH: left-recursive NEListRecordFieldPat to avoid shift/reduce conflict
--        with the trailing comma before `..` in PRecordOpen. Built reversed.
NEListRecordFieldPat :: { [GeneratedParser.Wok.Abs.RecordFieldPat] }
NEListRecordFieldPat
  : RecordFieldPat { [$1] }
  | NEListRecordFieldPat ',' RecordFieldPat { $3 : $1 }

PatRowTail :: { GeneratedParser.Wok.Abs.PatRowTail }
PatRowTail
  : '..' VarId { GeneratedParser.Wok.Abs.PRTNamed $2 }
  | '..' { GeneratedParser.Wok.Abs.PRTAnon }

ListAtomPat :: { [GeneratedParser.Wok.Abs.AtomPat] }
ListAtomPat
  : {- empty -} { [] } | AtomPat ListAtomPat { (:) $1 $2 }

ListPat :: { [GeneratedParser.Wok.Abs.Pat] }
ListPat
  : {- empty -} { [] }
  | Pat { (:[]) $1 }
  | Pat ',' ListPat { (:) $1 $3 }

Type :: { GeneratedParser.Wok.Abs.Type }
Type
  : Type1 '=>' Type { GeneratedParser.Wok.Abs.TQual $1 $3 }
  | Type1 '->' Type 'with' EffectRow { GeneratedParser.Wok.Abs.TWith $1 $3 $5 }
  | Type1 '->' Type { GeneratedParser.Wok.Abs.TFun $1 $3 }
  | Type1 { $1 }

EffectAtom :: { GeneratedParser.Wok.Abs.EffectAtom }
EffectAtom
  : ConId ListType2 { GeneratedParser.Wok.Abs.ERAtom $1 $2 }

EffectRow :: { GeneratedParser.Wok.Abs.EffectRow }
EffectRow
  : EffectAtom { GeneratedParser.Wok.Abs.EROne $1 }
  | EffectAtom VarSym EffectRow { GeneratedParser.Wok.Abs.ERPlus $1 $2 $3 }
  | 'eff' VarId { GeneratedParser.Wok.Abs.ERVarOnly $2 }
  | '..' { GeneratedParser.Wok.Abs.ERWildOnly }

Type1 :: { GeneratedParser.Wok.Abs.Type }
Type1
  : Type1 Type2 { GeneratedParser.Wok.Abs.TApp $1 $2 }
  | Type2 { $1 }
  | Type1 VarSym RowContrib { GeneratedParser.Wok.Abs.TExtend $1 $2 $3 }

Type2 :: { GeneratedParser.Wok.Abs.Type }
Type2
  : VarId { GeneratedParser.Wok.Abs.TVar $1 }
  | ModPath { GeneratedParser.Wok.Abs.TCon $1 }
  | '[' Type ']' { GeneratedParser.Wok.Abs.TList $2 }
  | '(' Type ',' ListType ')' { GeneratedParser.Wok.Abs.TTuple $2 $4 }
  | '(' Type ')' { GeneratedParser.Wok.Abs.TParen $2 }
  | '(' ')' { GeneratedParser.Wok.Abs.TUnit }
  | '(' 'row' VarId ')' { GeneratedParser.Wok.Abs.TRowArg $3 }
  | 'owned' Type2 { GeneratedParser.Wok.Abs.TOwned $2 }

RowContrib :: { GeneratedParser.Wok.Abs.RowContrib }
RowContrib
  : '{' ListRecordFieldType '}' { GeneratedParser.Wok.Abs.RCAnon $2 }
  | 'row' VarId { GeneratedParser.Wok.Abs.RCVar $2 }
  | '..' { GeneratedParser.Wok.Abs.RCWild }

ListType :: { [GeneratedParser.Wok.Abs.Type] }
ListType
  : {- empty -} { [] }
  | Type { (:[]) $1 }
  | Type ',' ListType { (:) $1 $3 }

ConDef :: { GeneratedParser.Wok.Abs.ConDef }
ConDef
  : ConId ListType2 { GeneratedParser.Wok.Abs.ConDef $1 $2 }
  | ConId '{' ListRecordFieldType '}' { GeneratedParser.Wok.Abs.ConDefRec $1 $3 }
  | '{' ListRecordFieldType '}' { GeneratedParser.Wok.Abs.ConDefRecElide $2 }

RecordFieldType :: { GeneratedParser.Wok.Abs.RecordFieldType }
RecordFieldType
  : VarId ':' Type { GeneratedParser.Wok.Abs.RFType $1 $3 }

ListRecordFieldType :: { [GeneratedParser.Wok.Abs.RecordFieldType] }
ListRecordFieldType
  : {- empty -} { [] }
  | RecordFieldType { (:[]) $1 }
  | RecordFieldType ',' ListRecordFieldType { (:) $1 $3 }

ListConDef :: { [GeneratedParser.Wok.Abs.ConDef] }
ListConDef
  : {- empty -} { [] }
  | ConDef { (:[]) $1 }
  | ConDef '|' ListConDef { (:) $1 $3 }

ListType2 :: { [GeneratedParser.Wok.Abs.Type] }
ListType2 : {- empty -} { [] } | Type2 ListType2 { (:) $1 $2 }

FixName :: { GeneratedParser.Wok.Abs.FixName }
FixName
  : VarSym { GeneratedParser.Wok.Abs.FNSym $1 }
  | VarId { GeneratedParser.Wok.Abs.FNAlpha $1 }

FixAssoc :: { GeneratedParser.Wok.Abs.FixAssoc }
FixAssoc
  : 'left' { GeneratedParser.Wok.Abs.FALeft }
  | 'right' { GeneratedParser.Wok.Abs.FARight }

FixRel :: { GeneratedParser.Wok.Abs.FixRel }
FixRel
  : 'tighter' 'than' FixName { GeneratedParser.Wok.Abs.FRTight $3 }
  | 'looser' 'than' FixName { GeneratedParser.Wok.Abs.FRLoose $3 }

ListFixRel :: { [GeneratedParser.Wok.Abs.FixRel] }
ListFixRel : {- empty -} { [] } | FixRel ListFixRel { (:) $1 $2 }

Exp :: { GeneratedParser.Wok.Abs.Exp }
Exp : Exp1 ListInfixTail { GeneratedParser.Wok.Abs.EExpr $1 $2 }

InfixTail :: { GeneratedParser.Wok.Abs.InfixTail }
InfixTail : InfixOp Exp1 { GeneratedParser.Wok.Abs.ITail $1 $2 }

ListInfixTail :: { [GeneratedParser.Wok.Abs.InfixTail] }
ListInfixTail
  : {- empty -} { [] } | InfixTail ListInfixTail { (:) $1 $2 }

InfixOp :: { GeneratedParser.Wok.Abs.InfixOp }
InfixOp
  : VarSym { GeneratedParser.Wok.Abs.IOSym $1 }
  | '`' VarId '`' { GeneratedParser.Wok.Abs.IOBT $2 }

Exp1 :: { GeneratedParser.Wok.Abs.Exp }
Exp1
  : Exp1 Exp2 { GeneratedParser.Wok.Abs.EApp $1 $2 } | Exp2 { $1 }

Exp2 :: { GeneratedParser.Wok.Abs.Exp }
Exp2
  : VarId { GeneratedParser.Wok.Abs.EVar $1 }
  | ConId { GeneratedParser.Wok.Abs.ECon $1 }
  | Exp2 '.' VarId { GeneratedParser.Wok.Abs.EProj $1 $3 }
  | Exp2 '.' ConId { GeneratedParser.Wok.Abs.EProjC $1 $3 }
  | ConId '{' ListRecordFieldExpr '}' { GeneratedParser.Wok.Abs.ERecord $1 $3 }
  | ConId '{' '..' Exp MaybeTrailing '}' { GeneratedParser.Wok.Abs.ERecordExt $1 $4 $5 }
  | WokInt { GeneratedParser.Wok.Abs.ELitI $1 }
  | String { GeneratedParser.Wok.Abs.ELitS $1 }
  | Char { GeneratedParser.Wok.Abs.ELitC $1 }
  | '(' Exp ')' { GeneratedParser.Wok.Abs.EParen $2 }
  | '(' VarSym ')' { GeneratedParser.Wok.Abs.EParenOp $2 }
  | '(' ')' { GeneratedParser.Wok.Abs.EUnit }
  | '[' ListExp ']' { GeneratedParser.Wok.Abs.EList $2 }
  | '(' Exp ',' ListExp ')' { GeneratedParser.Wok.Abs.ETuple $2 $4 }
  | '\\' ListAtomPat '->' Exp { GeneratedParser.Wok.Abs.ELam $2 $4 }
  | 'let' '{' ListLocalDecl '}' 'in' Exp { GeneratedParser.Wok.Abs.ELet $3 $6 }
  | 'case' Exp 'of' '{' ListAlt '}' { GeneratedParser.Wok.Abs.ECase $2 $5 }
  | 'if' Exp 'then' Exp 'else' Exp { GeneratedParser.Wok.Abs.EIf $2 $4 $6 }
  | 'with' '{' ListHandlerArm '}' Exp { GeneratedParser.Wok.Abs.EWith $3 $5 }
  | 'with' ConId ListConId '{' ListHandlerArm '}' Exp { GeneratedParser.Wok.Abs.EWithH $2 $3 $5 $7 }
  | 'with' VarId ListWithArg 'in' Exp { GeneratedParser.Wok.Abs.EWithRun $2 $3 $5 }
  | 'with' VarId '=' VarId ListWithArg 'in' Exp { GeneratedParser.Wok.Abs.EWithNamed $2 $4 $5 $7 }
  | 'with' VarId '=' ConId '{' ListHandlerArm '}' 'in' Exp { GeneratedParser.Wok.Abs.EWithNamedH $2 $4 $6 $9 }

MaybeTrailing :: { GeneratedParser.Wok.Abs.MaybeTrailing }
MaybeTrailing
  : {- empty -} { GeneratedParser.Wok.Abs.TFNone }
  | ',' ListRecordFieldExpr { GeneratedParser.Wok.Abs.TFSome $2 }

RecordFieldExpr :: { GeneratedParser.Wok.Abs.RecordFieldExpr }
RecordFieldExpr
  : VarId '=' Exp { GeneratedParser.Wok.Abs.RFExpr $1 $3 }

ListRecordFieldExpr :: { [GeneratedParser.Wok.Abs.RecordFieldExpr] }
ListRecordFieldExpr
  : {- empty -} { [] }
  | RecordFieldExpr { (:[]) $1 }
  | RecordFieldExpr ',' ListRecordFieldExpr { (:) $1 $3 }

WithArg :: { GeneratedParser.Wok.Abs.WithArg }
WithArg : Exp2 { GeneratedParser.Wok.Abs.WRArg $1 }

ListWithArg :: { [GeneratedParser.Wok.Abs.WithArg] }
ListWithArg
  : {- empty -} { [] } | WithArg ListWithArg { (:) $1 $2 }

HandlerArm :: { GeneratedParser.Wok.Abs.HandlerArm }
HandlerArm
  : ConId '.' VarId ListAtomPat '->' Exp { GeneratedParser.Wok.Abs.HArm $1 $3 $4 $6 }
  | VarId ListAtomPat '->' Exp { GeneratedParser.Wok.Abs.HUArm $1 $2 $4 }
  | VarId '=' Exp { GeneratedParser.Wok.Abs.HParam $1 $3 }

ListHandlerArm :: { [GeneratedParser.Wok.Abs.HandlerArm] }
ListHandlerArm
  : {- empty -} { [] }
  | HandlerArm { (:[]) $1 }
  | HandlerArm ';' ListHandlerArm { (:) $1 $3 }

ListConId :: { [GeneratedParser.Wok.Abs.ConId] }
ListConId : {- empty -} { [] } | ConId ListConId { (:) $1 $2 }

ListExp :: { [GeneratedParser.Wok.Abs.Exp] }
ListExp
  : {- empty -} { [] }
  | Exp { (:[]) $1 }
  | Exp ',' ListExp { (:) $1 $3 }

LocalDecl :: { GeneratedParser.Wok.Abs.LocalDecl }
LocalDecl
  : FunLHS '=' Exp MaybeWhere { GeneratedParser.Wok.Abs.LDEqn $1 $3 $4 }
  | SigName ListSigNameComma ':' Type { GeneratedParser.Wok.Abs.LDSig $1 $2 $4 }
  | '(' Pat ',' ListPat ')' '=' Exp { GeneratedParser.Wok.Abs.LDPat $2 $4 $7 }

ListLocalDecl :: { [GeneratedParser.Wok.Abs.LocalDecl] }
ListLocalDecl
  : {- empty -} { [] }
  | LocalDecl { (:[]) $1 }
  | LocalDecl ';' ListLocalDecl { (:) $1 $3 }

MaybeWhere :: { GeneratedParser.Wok.Abs.MaybeWhere }
MaybeWhere
  : {- empty -} { GeneratedParser.Wok.Abs.NoWhere }
  | 'where' '{' ListLocalDecl '}' { GeneratedParser.Wok.Abs.WithWh $3 }

Alt :: { GeneratedParser.Wok.Abs.Alt }
Alt
  : Pat '->' Exp MaybeWhere { GeneratedParser.Wok.Abs.AltC $1 $3 $4 }

ListAlt :: { [GeneratedParser.Wok.Abs.Alt] }
ListAlt
  : {- empty -} { [] }
  | Alt { (:[]) $1 }
  | Alt ';' ListAlt { (:) $1 $3 }

{

type Err = Either String

happyError :: [Token] -> Err a
happyError ts = Left $
  "syntax error at " ++ tokenPos ts ++
  case ts of
    []      -> []
    [Err _] -> " due to lexer error"
    t:_     -> " before `" ++ (prToken t) ++ "'"

myLexer :: Data.Text.Text -> [Token]
myLexer = tokens

}

