-- File generated by the BNF Converter (bnfc 2.9.6.3).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for GeneratedParser.

module GeneratedParser.Wok.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified GeneratedParser.Wok.Abs
import qualified Data.Text

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print GeneratedParser.Wok.Abs.WokInt where
  prt _ (GeneratedParser.Wok.Abs.WokInt (_,i)) = doc $ showString (Data.Text.unpack i)
instance Print GeneratedParser.Wok.Abs.ConId where
  prt _ (GeneratedParser.Wok.Abs.ConId (_,i)) = doc $ showString (Data.Text.unpack i)
instance Print GeneratedParser.Wok.Abs.VarId where
  prt _ (GeneratedParser.Wok.Abs.VarId (_,i)) = doc $ showString (Data.Text.unpack i)
instance Print GeneratedParser.Wok.Abs.VarSym where
  prt _ (GeneratedParser.Wok.Abs.VarSym (_,i)) = doc $ showString (Data.Text.unpack i)
instance Print GeneratedParser.Wok.Abs.Module where
  prt i = \case
    GeneratedParser.Wok.Abs.Module decls -> prPrec i 0 (concatD [prt 0 decls])

instance Print GeneratedParser.Wok.Abs.Decl where
  prt i = \case
    GeneratedParser.Wok.Abs.DEqn funlhs exp maybewhere -> prPrec i 0 (concatD [prt 0 funlhs, doc (showString "="), prt 0 exp, prt 0 maybewhere])
    GeneratedParser.Wok.Abs.DSig signame signamecommas type_ -> prPrec i 0 (concatD [prt 0 signame, prt 0 signamecommas, doc (showString ":"), prt 0 type_])
    GeneratedParser.Wok.Abs.DExtern signame signamecommas type_ -> prPrec i 0 (concatD [doc (showString "extern"), prt 0 signame, prt 0 signamecommas, doc (showString ":"), prt 0 type_])
    GeneratedParser.Wok.Abs.DData conid typarams condefs -> prPrec i 0 (concatD [doc (showString "data"), prt 0 conid, prt 0 typarams, doc (showString "="), prt 0 condefs])
    GeneratedParser.Wok.Abs.DExternData conid typarams condefs -> prPrec i 0 (concatD [doc (showString "extern"), doc (showString "data"), prt 0 conid, prt 0 typarams, doc (showString "="), prt 0 condefs])
    GeneratedParser.Wok.Abs.DExternType conid typarams -> prPrec i 0 (concatD [doc (showString "extern"), doc (showString "type"), prt 0 conid, prt 0 typarams])
    GeneratedParser.Wok.Abs.DEffect conid varids recordfieldtypes -> prPrec i 0 (concatD [doc (showString "effect"), prt 0 conid, prt 0 varids, doc (showString "="), doc (showString "{"), prt 0 recordfieldtypes, doc (showString "}")])
    GeneratedParser.Wok.Abs.DFixity fixname fixassoc fixrels -> prPrec i 0 (concatD [doc (showString "fixity"), prt 0 fixname, prt 0 fixassoc, prt 0 fixrels])
    GeneratedParser.Wok.Abs.DClass conid varids classentrys -> prPrec i 0 (concatD [doc (showString "class"), prt 0 conid, prt 0 varids, doc (showString "where"), doc (showString "{"), prt 0 classentrys, doc (showString "}")])
    GeneratedParser.Wok.Abs.DInstance insthead instentrys -> prPrec i 0 (concatD [doc (showString "instance"), prt 0 insthead, doc (showString "where"), doc (showString "{"), prt 0 instentrys, doc (showString "}")])
    GeneratedParser.Wok.Abs.DForeign conid str foreignfree foreignmembers -> prPrec i 0 (concatD [doc (showString "foreign"), doc (showString "module"), prt 0 conid, printString str, prt 0 foreignfree, doc (showString "where"), doc (showString "{"), prt 0 foreignmembers, doc (showString "}")])
    GeneratedParser.Wok.Abs.DModule modpath -> prPrec i 0 (concatD [doc (showString "module"), prt 0 modpath])
    GeneratedParser.Wok.Abs.DImport modpath -> prPrec i 0 (concatD [doc (showString "import"), prt 0 modpath])
    GeneratedParser.Wok.Abs.DUse modpath -> prPrec i 0 (concatD [doc (showString "use"), prt 0 modpath])
    GeneratedParser.Wok.Abs.DLocal decl -> prPrec i 0 (concatD [doc (showString "local"), prt 0 decl])
    GeneratedParser.Wok.Abs.DReserved reservedkw -> prPrec i 0 (concatD [prt 0 reservedkw])

instance Print GeneratedParser.Wok.Abs.ForeignFree where
  prt i = \case
    GeneratedParser.Wok.Abs.FFNone -> prPrec i 0 (concatD [])
    GeneratedParser.Wok.Abs.FFSym str -> prPrec i 0 (concatD [doc (showString "free"), printString str])

instance Print GeneratedParser.Wok.Abs.ForeignMember where
  prt i = \case
    GeneratedParser.Wok.Abs.FMPlain varid foreignsym type_ -> prPrec i 0 (concatD [prt 0 varid, prt 0 foreignsym, doc (showString ":"), prt 0 type_])
    GeneratedParser.Wok.Abs.FMOwned varid foreignsym type_ -> prPrec i 0 (concatD [doc (showString "owned"), prt 0 varid, prt 0 foreignsym, doc (showString ":"), prt 0 type_])

instance Print GeneratedParser.Wok.Abs.ForeignSym where
  prt i = \case
    GeneratedParser.Wok.Abs.FSNone -> prPrec i 0 (concatD [])
    GeneratedParser.Wok.Abs.FSName str -> prPrec i 0 (concatD [printString str])

instance Print [GeneratedParser.Wok.Abs.ForeignMember] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.InstHead where
  prt i = \case
    GeneratedParser.Wok.Abs.IHPlain conid types -> prPrec i 0 (concatD [prt 0 conid, prt 2 types])
    GeneratedParser.Wok.Abs.IHCtx constraints conid types -> prPrec i 0 (concatD [doc (showString "("), prt 0 constraints, doc (showString ")"), doc (showString "=>"), prt 0 conid, prt 2 types])

instance Print GeneratedParser.Wok.Abs.MethodName where
  prt i = \case
    GeneratedParser.Wok.Abs.MNBare varid -> prPrec i 0 (concatD [prt 0 varid])
    GeneratedParser.Wok.Abs.MNParen varsym -> prPrec i 0 (concatD [doc (showString "("), prt 0 varsym, doc (showString ")")])

instance Print GeneratedParser.Wok.Abs.ClassEntry where
  prt i = \case
    GeneratedParser.Wok.Abs.CESig methodname type_ -> prPrec i 0 (concatD [prt 0 methodname, doc (showString ":"), prt 0 type_])
    GeneratedParser.Wok.Abs.CEDefault funlhs exp -> prPrec i 0 (concatD [prt 0 funlhs, doc (showString "="), prt 0 exp])

instance Print [GeneratedParser.Wok.Abs.ClassEntry] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.InstEntry where
  prt i = \case
    GeneratedParser.Wok.Abs.IEImpl funlhs exp -> prPrec i 0 (concatD [prt 0 funlhs, doc (showString "="), prt 0 exp])

instance Print [GeneratedParser.Wok.Abs.InstEntry] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.Constraint where
  prt i = \case
    GeneratedParser.Wok.Abs.Constraint conid types -> prPrec i 0 (concatD [prt 0 conid, prt 2 types])

instance Print [GeneratedParser.Wok.Abs.Constraint] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [GeneratedParser.Wok.Abs.Decl] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.ModPath where
  prt i = \case
    GeneratedParser.Wok.Abs.MPName conid -> prPrec i 0 (concatD [prt 0 conid])
    GeneratedParser.Wok.Abs.MPDot modpath conid -> prPrec i 0 (concatD [prt 0 modpath, doc (showString "."), prt 0 conid])

instance Print GeneratedParser.Wok.Abs.ReservedKw where
  prt i = \case
    GeneratedParser.Wok.Abs.ReservedKw_contract -> prPrec i 0 (concatD [doc (showString "contract")])
    GeneratedParser.Wok.Abs.ReservedKw_type -> prPrec i 0 (concatD [doc (showString "type")])
    GeneratedParser.Wok.Abs.ReservedKw_deriving -> prPrec i 0 (concatD [doc (showString "deriving")])
    GeneratedParser.Wok.Abs.ReservedKw_forall -> prPrec i 0 (concatD [doc (showString "forall")])
    GeneratedParser.Wok.Abs.ReservedKw_do -> prPrec i 0 (concatD [doc (showString "do")])
    GeneratedParser.Wok.Abs.ReservedKw_record -> prPrec i 0 (concatD [doc (showString "record")])
    GeneratedParser.Wok.Abs.ReservedKw_row -> prPrec i 0 (concatD [doc (showString "row")])
    GeneratedParser.Wok.Abs.ReservedKw_fun -> prPrec i 0 (concatD [doc (showString "fun")])
    GeneratedParser.Wok.Abs.ReservedKw_ctl -> prPrec i 0 (concatD [doc (showString "ctl")])

instance Print GeneratedParser.Wok.Abs.SigName where
  prt i = \case
    GeneratedParser.Wok.Abs.SNBare varid -> prPrec i 0 (concatD [prt 0 varid])
    GeneratedParser.Wok.Abs.SNParen varsym -> prPrec i 0 (concatD [doc (showString "("), prt 0 varsym, doc (showString ")")])

instance Print GeneratedParser.Wok.Abs.SigNameComma where
  prt i = \case
    GeneratedParser.Wok.Abs.SNCons signame -> prPrec i 0 (concatD [doc (showString ","), prt 0 signame])

instance Print [GeneratedParser.Wok.Abs.SigNameComma] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [GeneratedParser.Wok.Abs.VarId] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print GeneratedParser.Wok.Abs.TyParam where
  prt i = \case
    GeneratedParser.Wok.Abs.TPPlain varid -> prPrec i 0 (concatD [prt 0 varid])
    GeneratedParser.Wok.Abs.TPRow varid -> prPrec i 0 (concatD [doc (showString "("), doc (showString "row"), prt 0 varid, doc (showString ")")])

instance Print [GeneratedParser.Wok.Abs.TyParam] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print GeneratedParser.Wok.Abs.FunLHS where
  prt i = \case
    GeneratedParser.Wok.Abs.LHSPre funname atompats -> prPrec i 0 (concatD [prt 0 funname, prt 0 atompats])
    GeneratedParser.Wok.Abs.LHSInfSym atompat1 varsym atompat2 -> prPrec i 0 (concatD [prt 0 atompat1, prt 0 varsym, prt 0 atompat2])
    GeneratedParser.Wok.Abs.LHSInfBT atompat1 varid atompat2 -> prPrec i 0 (concatD [prt 0 atompat1, doc (showString "`"), prt 0 varid, doc (showString "`"), prt 0 atompat2])

instance Print GeneratedParser.Wok.Abs.FunName where
  prt i = \case
    GeneratedParser.Wok.Abs.FNBare varid -> prPrec i 0 (concatD [prt 0 varid])
    GeneratedParser.Wok.Abs.FNBareSym varsym -> prPrec i 0 (concatD [prt 0 varsym])
    GeneratedParser.Wok.Abs.FNParen varsym -> prPrec i 0 (concatD [doc (showString "("), prt 0 varsym, doc (showString ")")])

instance Print GeneratedParser.Wok.Abs.Pat where
  prt i = \case
    GeneratedParser.Wok.Abs.PApp modpath atompat atompats -> prPrec i 0 (concatD [prt 0 modpath, prt 0 atompat, prt 0 atompats])
    GeneratedParser.Wok.Abs.PCons atompat pat -> prPrec i 0 (concatD [prt 0 atompat, doc (showString "::"), prt 0 pat])
    GeneratedParser.Wok.Abs.PAtom atompat -> prPrec i 0 (concatD [prt 0 atompat])

instance Print GeneratedParser.Wok.Abs.AtomPat where
  prt i = \case
    GeneratedParser.Wok.Abs.APVar varid -> prPrec i 0 (concatD [prt 0 varid])
    GeneratedParser.Wok.Abs.APCon modpath -> prPrec i 0 (concatD [prt 0 modpath])
    GeneratedParser.Wok.Abs.APWild -> prPrec i 0 (concatD [doc (showString "_")])
    GeneratedParser.Wok.Abs.APLitI wokint -> prPrec i 0 (concatD [prt 0 wokint])
    GeneratedParser.Wok.Abs.APLitS str -> prPrec i 0 (concatD [printString str])
    GeneratedParser.Wok.Abs.APLitC c -> prPrec i 0 (concatD [prt 0 c])
    GeneratedParser.Wok.Abs.APTuple pat pats -> prPrec i 0 (concatD [doc (showString "("), prt 0 pat, doc (showString ","), prt 0 pats, doc (showString ")")])
    GeneratedParser.Wok.Abs.APList pats -> prPrec i 0 (concatD [doc (showString "["), prt 0 pats, doc (showString "]")])
    GeneratedParser.Wok.Abs.APParen pat -> prPrec i 0 (concatD [doc (showString "("), prt 0 pat, doc (showString ")")])
    GeneratedParser.Wok.Abs.PUnit -> prPrec i 0 (concatD [doc (showString "("), doc (showString ")")])
    GeneratedParser.Wok.Abs.APAs atompat varid -> prPrec i 0 (concatD [prt 0 atompat, doc (showString "as"), prt 0 varid])
    GeneratedParser.Wok.Abs.PRecord conid recordfieldpats -> prPrec i 0 (concatD [prt 0 conid, doc (showString "{"), prt 0 recordfieldpats, doc (showString "}")])
    GeneratedParser.Wok.Abs.PRecordOpen conid recordfieldpats patrowtail -> prPrec i 0 (concatD [prt 0 conid, doc (showString "{"), prt 0 recordfieldpats, doc (showString ","), prt 0 patrowtail, doc (showString "}")])
    GeneratedParser.Wok.Abs.PRecordWild conid patrowtail -> prPrec i 0 (concatD [prt 0 conid, doc (showString "{"), prt 0 patrowtail, doc (showString "}")])

instance Print GeneratedParser.Wok.Abs.RecordFieldPat where
  prt i = \case
    GeneratedParser.Wok.Abs.RFPat varid pat -> prPrec i 0 (concatD [prt 0 varid, doc (showString "="), prt 0 pat])

instance Print [GeneratedParser.Wok.Abs.RecordFieldPat] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.PatRowTail where
  prt i = \case
    GeneratedParser.Wok.Abs.PRTNamed varid -> prPrec i 0 (concatD [doc (showString ".."), prt 0 varid])
    GeneratedParser.Wok.Abs.PRTAnon -> prPrec i 0 (concatD [doc (showString "..")])

instance Print [GeneratedParser.Wok.Abs.AtomPat] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [GeneratedParser.Wok.Abs.Pat] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.Type where
  prt i = \case
    GeneratedParser.Wok.Abs.TQual type_1 type_2 -> prPrec i 0 (concatD [prt 1 type_1, doc (showString "=>"), prt 0 type_2])
    GeneratedParser.Wok.Abs.TWith type_1 type_2 effectrow -> prPrec i 0 (concatD [prt 1 type_1, doc (showString "->"), prt 0 type_2, doc (showString "with"), prt 0 effectrow])
    GeneratedParser.Wok.Abs.TFun type_1 type_2 -> prPrec i 0 (concatD [prt 1 type_1, doc (showString "->"), prt 0 type_2])
    GeneratedParser.Wok.Abs.TApp type_1 type_2 -> prPrec i 1 (concatD [prt 1 type_1, prt 2 type_2])
    GeneratedParser.Wok.Abs.TVar varid -> prPrec i 2 (concatD [prt 0 varid])
    GeneratedParser.Wok.Abs.TCon modpath -> prPrec i 2 (concatD [prt 0 modpath])
    GeneratedParser.Wok.Abs.TList type_ -> prPrec i 2 (concatD [doc (showString "["), prt 0 type_, doc (showString "]")])
    GeneratedParser.Wok.Abs.TTuple type_ types -> prPrec i 2 (concatD [doc (showString "("), prt 0 type_, doc (showString ","), prt 0 types, doc (showString ")")])
    GeneratedParser.Wok.Abs.TParen type_ -> prPrec i 2 (concatD [doc (showString "("), prt 0 type_, doc (showString ")")])
    GeneratedParser.Wok.Abs.TUnit -> prPrec i 2 (concatD [doc (showString "("), doc (showString ")")])
    GeneratedParser.Wok.Abs.TRowArg varid -> prPrec i 2 (concatD [doc (showString "("), doc (showString "row"), prt 0 varid, doc (showString ")")])
    GeneratedParser.Wok.Abs.TOwned type_ -> prPrec i 2 (concatD [doc (showString "owned"), prt 2 type_])
    GeneratedParser.Wok.Abs.TExtend type_ varsym rowcontrib -> prPrec i 1 (concatD [prt 1 type_, prt 0 varsym, prt 0 rowcontrib])

instance Print GeneratedParser.Wok.Abs.EffectAtom where
  prt i = \case
    GeneratedParser.Wok.Abs.ERAtom conid types -> prPrec i 0 (concatD [prt 0 conid, prt 2 types])

instance Print GeneratedParser.Wok.Abs.EffectRow where
  prt i = \case
    GeneratedParser.Wok.Abs.EROne effectatom -> prPrec i 0 (concatD [prt 0 effectatom])
    GeneratedParser.Wok.Abs.ERPlus effectatom varsym effectrow -> prPrec i 0 (concatD [prt 0 effectatom, prt 0 varsym, prt 0 effectrow])
    GeneratedParser.Wok.Abs.ERVarOnly varid -> prPrec i 0 (concatD [doc (showString "eff"), prt 0 varid])
    GeneratedParser.Wok.Abs.ERWildOnly -> prPrec i 0 (concatD [doc (showString "..")])

instance Print GeneratedParser.Wok.Abs.RowContrib where
  prt i = \case
    GeneratedParser.Wok.Abs.RCAnon recordfieldtypes -> prPrec i 0 (concatD [doc (showString "{"), prt 0 recordfieldtypes, doc (showString "}")])
    GeneratedParser.Wok.Abs.RCVar varid -> prPrec i 0 (concatD [doc (showString "row"), prt 0 varid])
    GeneratedParser.Wok.Abs.RCWild -> prPrec i 0 (concatD [doc (showString "..")])

instance Print [GeneratedParser.Wok.Abs.Type] where
  prt 2 [] = concatD []
  prt 2 (x:xs) = concatD [prt 2 x, prt 2 xs]
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.ConDef where
  prt i = \case
    GeneratedParser.Wok.Abs.ConDef conid types -> prPrec i 0 (concatD [prt 0 conid, prt 2 types])
    GeneratedParser.Wok.Abs.ConDefRec conid recordfieldtypes -> prPrec i 0 (concatD [prt 0 conid, doc (showString "{"), prt 0 recordfieldtypes, doc (showString "}")])
    GeneratedParser.Wok.Abs.ConDefRecElide recordfieldtypes -> prPrec i 0 (concatD [doc (showString "{"), prt 0 recordfieldtypes, doc (showString "}")])

instance Print GeneratedParser.Wok.Abs.RecordFieldType where
  prt i = \case
    GeneratedParser.Wok.Abs.RFType varid type_ -> prPrec i 0 (concatD [prt 0 varid, doc (showString ":"), prt 0 type_])

instance Print [GeneratedParser.Wok.Abs.RecordFieldType] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [GeneratedParser.Wok.Abs.ConDef] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "|"), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.FixName where
  prt i = \case
    GeneratedParser.Wok.Abs.FNSym varsym -> prPrec i 0 (concatD [prt 0 varsym])
    GeneratedParser.Wok.Abs.FNAlpha varid -> prPrec i 0 (concatD [prt 0 varid])

instance Print GeneratedParser.Wok.Abs.FixAssoc where
  prt i = \case
    GeneratedParser.Wok.Abs.FALeft -> prPrec i 0 (concatD [doc (showString "left")])
    GeneratedParser.Wok.Abs.FARight -> prPrec i 0 (concatD [doc (showString "right")])

instance Print GeneratedParser.Wok.Abs.FixRel where
  prt i = \case
    GeneratedParser.Wok.Abs.FRTight fixname -> prPrec i 0 (concatD [doc (showString "tighter"), doc (showString "than"), prt 0 fixname])
    GeneratedParser.Wok.Abs.FRLoose fixname -> prPrec i 0 (concatD [doc (showString "looser"), doc (showString "than"), prt 0 fixname])

instance Print [GeneratedParser.Wok.Abs.FixRel] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print GeneratedParser.Wok.Abs.Exp where
  prt i = \case
    GeneratedParser.Wok.Abs.EExpr exp infixtails -> prPrec i 0 (concatD [prt 1 exp, prt 0 infixtails])
    GeneratedParser.Wok.Abs.EApp exp1 exp2 -> prPrec i 1 (concatD [prt 1 exp1, prt 2 exp2])
    GeneratedParser.Wok.Abs.EVar varid -> prPrec i 2 (concatD [prt 0 varid])
    GeneratedParser.Wok.Abs.ECon conid -> prPrec i 2 (concatD [prt 0 conid])
    GeneratedParser.Wok.Abs.EProj exp varid -> prPrec i 2 (concatD [prt 2 exp, doc (showString "."), prt 0 varid])
    GeneratedParser.Wok.Abs.EProjC exp conid -> prPrec i 2 (concatD [prt 2 exp, doc (showString "."), prt 0 conid])
    GeneratedParser.Wok.Abs.ERecord conid recordfieldexprs -> prPrec i 2 (concatD [prt 0 conid, doc (showString "{"), prt 0 recordfieldexprs, doc (showString "}")])
    GeneratedParser.Wok.Abs.ERecordExt conid exp maybetrailing -> prPrec i 2 (concatD [prt 0 conid, doc (showString "{"), doc (showString ".."), prt 0 exp, prt 0 maybetrailing, doc (showString "}")])
    GeneratedParser.Wok.Abs.ELitI wokint -> prPrec i 2 (concatD [prt 0 wokint])
    GeneratedParser.Wok.Abs.ELitS str -> prPrec i 2 (concatD [printString str])
    GeneratedParser.Wok.Abs.ELitC c -> prPrec i 2 (concatD [prt 0 c])
    GeneratedParser.Wok.Abs.EParen exp -> prPrec i 2 (concatD [doc (showString "("), prt 0 exp, doc (showString ")")])
    GeneratedParser.Wok.Abs.EParenOp varsym -> prPrec i 2 (concatD [doc (showString "("), prt 0 varsym, doc (showString ")")])
    GeneratedParser.Wok.Abs.EUnit -> prPrec i 2 (concatD [doc (showString "("), doc (showString ")")])
    GeneratedParser.Wok.Abs.EList exps -> prPrec i 2 (concatD [doc (showString "["), prt 0 exps, doc (showString "]")])
    GeneratedParser.Wok.Abs.ETuple exp exps -> prPrec i 2 (concatD [doc (showString "("), prt 0 exp, doc (showString ","), prt 0 exps, doc (showString ")")])
    GeneratedParser.Wok.Abs.ELam atompats exp -> prPrec i 2 (concatD [doc (showString "\\"), prt 0 atompats, doc (showString "->"), prt 0 exp])
    GeneratedParser.Wok.Abs.ELet localdecls exp -> prPrec i 2 (concatD [doc (showString "let"), doc (showString "{"), prt 0 localdecls, doc (showString "}"), doc (showString "in"), prt 0 exp])
    GeneratedParser.Wok.Abs.ECase exp alts -> prPrec i 2 (concatD [doc (showString "case"), prt 0 exp, doc (showString "of"), doc (showString "{"), prt 0 alts, doc (showString "}")])
    GeneratedParser.Wok.Abs.EIf exp1 exp2 exp3 -> prPrec i 2 (concatD [doc (showString "if"), prt 0 exp1, doc (showString "then"), prt 0 exp2, doc (showString "else"), prt 0 exp3])
    GeneratedParser.Wok.Abs.EWith handlerarms exp -> prPrec i 2 (concatD [doc (showString "with"), doc (showString "{"), prt 0 handlerarms, doc (showString "}"), prt 0 exp])
    GeneratedParser.Wok.Abs.EWithH conid conids handlerarms exp -> prPrec i 2 (concatD [doc (showString "with"), prt 0 conid, prt 0 conids, doc (showString "{"), prt 0 handlerarms, doc (showString "}"), prt 0 exp])
    GeneratedParser.Wok.Abs.EWithRun varid withargs exp -> prPrec i 2 (concatD [doc (showString "with"), prt 0 varid, prt 0 withargs, doc (showString "in"), prt 0 exp])
    GeneratedParser.Wok.Abs.EWithNamed varid1 varid2 withargs exp -> prPrec i 2 (concatD [doc (showString "with"), prt 0 varid1, doc (showString "="), prt 0 varid2, prt 0 withargs, doc (showString "in"), prt 0 exp])
    GeneratedParser.Wok.Abs.EWithNamedH varid conid handlerarms exp -> prPrec i 2 (concatD [doc (showString "with"), prt 0 varid, doc (showString "="), prt 0 conid, doc (showString "{"), prt 0 handlerarms, doc (showString "}"), doc (showString "in"), prt 0 exp])

instance Print GeneratedParser.Wok.Abs.InfixTail where
  prt i = \case
    GeneratedParser.Wok.Abs.ITail infixop exp -> prPrec i 0 (concatD [prt 0 infixop, prt 1 exp])

instance Print [GeneratedParser.Wok.Abs.InfixTail] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print GeneratedParser.Wok.Abs.InfixOp where
  prt i = \case
    GeneratedParser.Wok.Abs.IOSym varsym -> prPrec i 0 (concatD [prt 0 varsym])
    GeneratedParser.Wok.Abs.IOBT varid -> prPrec i 0 (concatD [doc (showString "`"), prt 0 varid, doc (showString "`")])

instance Print GeneratedParser.Wok.Abs.MaybeTrailing where
  prt i = \case
    GeneratedParser.Wok.Abs.TFNone -> prPrec i 0 (concatD [])
    GeneratedParser.Wok.Abs.TFSome recordfieldexprs -> prPrec i 0 (concatD [doc (showString ","), prt 0 recordfieldexprs])

instance Print GeneratedParser.Wok.Abs.RecordFieldExpr where
  prt i = \case
    GeneratedParser.Wok.Abs.RFExpr varid exp -> prPrec i 0 (concatD [prt 0 varid, doc (showString "="), prt 0 exp])

instance Print [GeneratedParser.Wok.Abs.RecordFieldExpr] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.WithArg where
  prt i = \case
    GeneratedParser.Wok.Abs.WRArg exp -> prPrec i 0 (concatD [prt 2 exp])

instance Print [GeneratedParser.Wok.Abs.WithArg] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print GeneratedParser.Wok.Abs.HandlerArm where
  prt i = \case
    GeneratedParser.Wok.Abs.HArm conid varid atompats exp -> prPrec i 0 (concatD [prt 0 conid, doc (showString "."), prt 0 varid, prt 0 atompats, doc (showString "->"), prt 0 exp])
    GeneratedParser.Wok.Abs.HUArm varid atompats exp -> prPrec i 0 (concatD [prt 0 varid, prt 0 atompats, doc (showString "->"), prt 0 exp])
    GeneratedParser.Wok.Abs.HParam varid exp -> prPrec i 0 (concatD [prt 0 varid, doc (showString "="), prt 0 exp])

instance Print [GeneratedParser.Wok.Abs.HandlerArm] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [GeneratedParser.Wok.Abs.ConId] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [GeneratedParser.Wok.Abs.Exp] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.LocalDecl where
  prt i = \case
    GeneratedParser.Wok.Abs.LDEqn funlhs exp maybewhere -> prPrec i 0 (concatD [prt 0 funlhs, doc (showString "="), prt 0 exp, prt 0 maybewhere])
    GeneratedParser.Wok.Abs.LDSig signame signamecommas type_ -> prPrec i 0 (concatD [prt 0 signame, prt 0 signamecommas, doc (showString ":"), prt 0 type_])
    GeneratedParser.Wok.Abs.LDPat pat pats exp -> prPrec i 0 (concatD [doc (showString "("), prt 0 pat, doc (showString ","), prt 0 pats, doc (showString ")"), doc (showString "="), prt 0 exp])

instance Print [GeneratedParser.Wok.Abs.LocalDecl] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print GeneratedParser.Wok.Abs.MaybeWhere where
  prt i = \case
    GeneratedParser.Wok.Abs.NoWhere -> prPrec i 0 (concatD [])
    GeneratedParser.Wok.Abs.WithWh localdecls -> prPrec i 0 (concatD [doc (showString "where"), doc (showString "{"), prt 0 localdecls, doc (showString "}")])

instance Print GeneratedParser.Wok.Abs.Alt where
  prt i = \case
    GeneratedParser.Wok.Abs.AltC pat exp maybewhere -> prPrec i 0 (concatD [prt 0 pat, doc (showString "->"), prt 0 exp, prt 0 maybewhere])

instance Print [GeneratedParser.Wok.Abs.Alt] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]
