#!/usr/bin/env python3
"""Patch genhtml's output: real title, clickable commit, machine-readable footer.

    coverage-postprocess.py <html-dir> --commit <sha> --repo WokML/wokml \
        --date <iso8601> --run <url>

genhtml has no templating worth the name, so the three things a published
report needs are added afterwards:

  * a title that says what the page IS, rather than "LCOV - <tracefile>"
  * the commit rendered as a link to GitHub, so the report can be traced back
    to the code it measured in one click instead of a copy-paste
  * a footer, and a <link rel="alternate">, pointing at the JSON

The footer is aimed at scrapers as much as people. An LLM asked "what is
untested in wok" should not have to parse 86 files of table markup to find
out; it should be told, on the page, that a JSON document exists and what is
in it.
"""

from __future__ import annotations

import argparse
import html
import pathlib
import re
import sys

TITLE = "WokML compiler code coverage report (LCOV)"


def build_footer(commit: str, repo: str, date: str, run: str, base: str) -> str:
    c = html.escape(commit)
    curl = f"https://github.com/{html.escape(repo)}/commit/{c}"
    run_html = (
        f'<a href="{html.escape(run)}">Github CI run</a>' if run else "a local build"
    )
    return f"""
<hr>
<table width="100%" border="0" cellspacing="0" cellpadding="4">
<tr><td>
<h3 id="machine-readable">Machine-readable coverage data</h3>
<p>This page is generated. If you are a tool, a script, or an LLM, read the
JSON instead of scraping this HTML &mdash; it is the same measurement, exact,
and it names the individual uncovered lines.</p>
<ul>
<li><code><a href="{base}/coverage.json">{base}/coverage.json</a></code>
    &mdash; the full report in one document: per-file line and function totals,
    plus <code>uncovered_lines</code> and <code>uncovered_functions</code> for
    every file. Schema <code>wok-coverage/1</code>.</li>
<li><code><a href="{base}/build.json">{base}/build.json</a></code>
    &mdash; provenance only: which commit was measured, when, and by which CI
    run.</li>
<li><code><a href="{base}/coverage.info">{base}/coverage.info</a></code>
    &mdash; the raw lcov tracefile these were derived from.</li>
</ul>
<p>Every artifact here is stamped with the commit it measured and the run that
produced it: commit <a href="{curl}"><code>{c}</code></a>, dated
{html.escape(date)}, built by {run_html}. The totals in
<code>coverage.json</code> are checked against lcov&rsquo;s own summary before
publishing, so the JSON and this page cannot disagree.</p>
</td></tr>
</table>
"""


def patch(path: pathlib.Path, commit: str, repo: str, footer: str, base: str) -> bool:
    text = original = path.read_text(encoding="utf-8", errors="replace")

    # Two titles, and they are different elements: the <title> tag drives the
    # browser tab and search results, while <td class="title"> is the heading
    # a reader actually sees ("LCOV - code coverage report"). Changing only
    # the first leaves the page still announcing itself as generic lcov output.
    text = re.sub(
        r"<title>.*?</title>", f"<title>{TITLE}</title>", text, count=1, flags=re.S
    )
    text = re.sub(
        r'(<td[^>]*class="title"[^>]*>).*?(</td>)',
        lambda m: m.group(1) + TITLE + m.group(2),
        text,
        flags=re.S,
    )
    # The "Generated by: LCOV version ..." line at the foot is left alone --
    # that is tool attribution, and it should stay accurate.

    # Point discovery tools at the JSON from the document head.
    if 'rel="alternate"' not in text:
        text = text.replace(
            "</head>",
            f'  <link rel="alternate" type="application/json" '
            f'href="{base}/coverage.json" title="coverage data">\n</head>',
            1,
        )

    # The short SHA appears in genhtml's "Test:" row, which is where --title
    # lands. Link only the bare hash, and only when it is not already a link:
    # genhtml rewrites this directory on every run, so a second pass should
    # never happen -- but if it does, it must not wrap the anchor in another.
    already_linked = f"/commit/{commit}" in text
    if commit and commit not in ("unknown", "") and not already_linked:
        text = re.sub(
            rf"(?<!/){re.escape(commit)}(?![\w/\"'>])",
            f'<a href="https://github.com/{repo}/commit/{commit}">{commit}</a>',
            text,
        )

    # Footer last, so the link rewrite above cannot touch it twice.
    if "machine-readable" not in text:
        text = text.replace("</body>", footer + "</body>", 1)

    if text != original:
        path.write_text(text, encoding="utf-8")
        return True
    return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("html_dir")
    ap.add_argument("--commit", required=True)
    ap.add_argument("--repo", default="WokML/wokml")
    ap.add_argument("--date", default="")
    ap.add_argument("--run", default="")
    ap.add_argument("--base", default="https://coverage.wokml.org")
    args = ap.parse_args()

    root = pathlib.Path(args.html_dir)
    if not root.is_dir():
        print(f"postprocess: {root} is not a directory", file=sys.stderr)
        return 1

    footer = build_footer(args.commit, args.repo, args.date, args.run, args.base)
    pages = sorted(root.rglob("*.html"))
    if not pages:
        print(f"postprocess: no HTML under {root}", file=sys.stderr)
        return 1

    changed = sum(patch(p, args.commit, args.repo, footer, args.base) for p in pages)
    print(f"postprocess: retitled and stamped {changed}/{len(pages)} pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
